### ISSUE TITLE
Exception in module binary during input validation in SetLayer()

### ISSUE THREAD

**Issue by Markus-Berger** [CodingGeoInfo/Prototyp#8]
Die neue Version von buffer.exe wirft eine Exception wenn man ein Import-Modul angeschlossen hat, wohl irgendwo während die SetLayer()-Methode im ControlConnectorService mit der VectorData Bibliothek arbeitet. Der Fehler tritt nicht auf wenn man den Server direkt aus VS startet (https://github.com/Markus-Berger/GrpcDemo) und sich so auf den passenden Port "mogelt".

Auf Server-Seite:

```
fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'SetLayer'.
System.BadImageFormatException: Could not load file or assembly 'MaxRev.Gdal.Core, Version=3.3.3.120, Culture=neutral, PublicKeyToken=null'. Es wurde versucht, eine Datei mit einem falschen Format zu laden.
File name: 'MaxRev.Gdal.Core, Version=3.3.3.120, Culture=neutral, PublicKeyToken=null'
   at GrpcServer.Elements.VectorData.HandleHeader(Header MyHeader)
   at GrpcServer.Elements.VectorData.HandleNameAndCRS()
   at GrpcServer.Elements.VectorData..ctor(Byte[] VecArray)
   at GrpcServer.ControlConnectorService.SetLayer(IAsyncStreamReader`1 requestStream, ServerCallContext context)
   at Grpc.Shared.Server.ClientStreamingServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, IAsyncStreamReader`1 requestStream)
   at Grpc.Shared.Server.ClientStreamingServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, IAsyncStreamReader`1 requestStream)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ClientStreamingServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
```

Auf Client-Seite:
```
Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")
   at Prototyp.MainWindow.UploadChunks(Node_Module targetNode, Int32 targetChannel, List`1 chunks, IProgress`1 progress) in C:\Users\marku\source\repos\Prototyp\Prototyp\MainWindow.xaml.cs:line 876
   at Prototyp.MainWindow.PlayButton_Click(Object sender, RoutedEventArgs e) in C:\Users\marku\source\repos\Prototyp\Prototyp\MainWindow.xaml.cs:line 836
```

**Comment by Croonenbroeck** [comment]
Problem gefunden: Beim Publish nicht nach 32-Bit-Compile-Target ("Win-x86"), sondern nach 64 Bit kompilieren, da eine 32-Bit-Binary die 64-Bit-Bibliotheken von GDAL nicht aufrufen kann.
